version: "3.8"
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    # volumes:
    #   - .:/app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: DEV
      TASK_SERVICE: http://localhost:4000
