import React from "react";
import Head from "next/head";
import { Fira_Code } from "next/font/google";
import styles from "./layout.module.css";
import { Sidebar } from "@/components/Sidebar/Sidebar";
import "./globals.css";
import { initializeMasterData } from "@/masterData/server/getMasterData";
import { ProviderWrapper } from "./ProviderWrapper";

const firaCode = Fira_Code({
  variable: "--font-fira-code",
  subsets: ["latin"],
});

export default async function Layout({
  children,
}: React.PropsWithChildren<{}>) {
  await initializeMasterData();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <html>
        <body>
          <ProviderWrapper>
            <div className={firaCode.variable}>
              <header></header>
              <main className={styles.main}>
                <Sidebar />
                {children}
              </main>
              <footer></footer>
            </div>
          </ProviderWrapper>
        </body>
      </html>
    </>
  );
}
